let enterLKString = "Вход в личный кабинет"
let jobSearchString = "Поиск работы"
let emailPlaceholderString = "Электронная почта или телефон"
let continueString = "Продолжить"
let enterWithPWString = "Войти с паролем"
let employeeSearchHeaderString = "Поиск сотрудников"
let employeeSearchTextString = "Размещение вакансий и доступ к базе резюме"
let employeeSearchButtonString = "Я ищу сотрудников"
